{% set name = "datashader" %}
{% set version = "0.14.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/datashader-{{ version }}.tar.gz
  sha256: 0241e611f951be3245972708e5a769bb183afbfceeec3cf2eef6d80af7756fbd
  patches:
    # numpy has removed the warnings symbol from the init.py file so np.warnings is not valid in newer versions of numpy. 
    # See https://github.com/holoviz/datashader/pull/1176
    # The patch should be removed after the next release of datashader.
    - 0001_do_not_use_warnings_from_numpy.patch
    # Fixed in the main branch of datashader, but not yet released, see https://github.com/holoviz/datashader/commit/31b31826d74da38e4878f87c3e44511d08d302df
    - 0002_fix_inspect_has_no_attribute_getargspec.patch

build:
  number: 1
  # Currently it's not available on s390x:
  # There are missing datashape, numba, fastparquet, netcdf4.
  skip: True  # [py<37 or s390x]
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  entry_points:
    - datashader = datashader.__main__:main

requirements:
  build:
    - m2-patch  # [win]
    - patch     # [not win]
  host:
    - python
    - pip
    - param
    - pyct
    - setuptools
    - wheel
  run:
    - python
    - colorcet
    - dask-core
    - datashape
    - numba >=0.51
    - numpy
    - pandas
    - param
    - pillow
    - pyct
    - requests
    - scipy
    - toolz
    - xarray

test:
  imports:
    - datashader
  requires:
    - fastparquet
    - flake8
    - holoviews
    - nbsmoke >0.5.0
    - netcdf4
    - pip
    - pytest
    - pytest-benchmark
  commands:
    - pip check || true    # [not win]
    - pip check || exit 0  # [win]
    - datashader --version
    - datashader --help
    - datashader copy-examples --path=. --force
    # just run one notebook for now; increase in the future if notebooks can be run quickly with test/tiny data
    - pytest --nbsmoke-run -k ".ipynb" getting_started/2_Pipeline.ipynb

about:
  home: https://datashader.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Data visualization toolchain based on aggregating into a grid
  description: |
    Datashader is a data rasterization pipeline for automating the process of
    creating meaningful representations of large amounts of data.
  doc_url: https://datashader.org
  dev_url: https://github.com/holoviz/datashader

extra:
  recipe-maintainers:
    - jbednar
    - ocefpaf
    - philippjfr
    - jsignell
