{% set name = "datashader" %}
{% set version = "0.19.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: beab445a44ac5f1dbc3f562c85d595c886a29dce4cc85eeb9a50723b729d57a2

build:
  number: 0
  skip: true  # [py<310]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python
    - pip
    - hatch-vcs
    - hatchling
  run:
    - python
    - colorcet
    - multipledispatch
    - numba
    - numpy
    - pandas
    - param
    - pyct
    - requests
    - scipy
    - toolz
    - packaging
    - xarray

test:
  imports:
    - datashader
    - datashader.antialias
    - datashader.bundling
    - datashader.colors
    - datashader.compiler
    - datashader.composite
    - datashader.core
    - datashader.data_libraries
    - datashader.datashape
    - datashader.datashape.coretypes
    - datashader.datashape.discovery
    - datashader.datashape.parser
    - datashader.datashape.predicates
    - datashader.datashape.user
    - datashader.datashape.util
    - datashader.datashape.util.testing
    - datashader.datatypes
    - datashader.glyphs
    - datashader.glyphs.area
    - datashader.glyphs.glyph
    - datashader.glyphs.line
    - datashader.glyphs.points
    - datashader.glyphs.quadmesh
    - datashader.glyphs.trimesh
    - datashader.layout
    - datashader.macros
    - datashader.mpl_ext
    - datashader.resampling
    - datashader.tiles
    - datashader.transfer_functions
    - datashader.utils
  requires:
    - pip
    - pytest
    - matplotlib
    - netcdf4
    - hypothesis
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest --pyargs datashader.tests

about:
  home: https://datashader.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Data visualization toolchain based on aggregating into a grid
  description: |
    Datashader is a data rasterization pipeline for automating the process of
    creating meaningful representations of large amounts of data.
  doc_url: https://datashader.org
  dev_url: https://github.com/holoviz/datashader

extra:
  recipe-maintainers:
    - jbednar
    - ocefpaf
    - philippjfr
    - jsignell