{% set name = "datashader" %}
{% set version = "0.14.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/datashader-{{ version }}.tar.gz
  sha256: abc68ea6e243e9a5fd9bd8cf9bd3d8e6f6460492fa2697fea4f1db71054e24b8

build:
  number: 0
  # Currently it's not available on s390x:
  # There are missing datashape, numba, fastparquet, netcdf4.
  skip: True  # [py<37 or s390x]
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  entry_points:
    - datashader = datashader.__main__:main

requirements:
  host:
    - python
    - pip
    - param
    - pyct
    - setuptools
    - wheel
  run:
    - python
    - colorcet >=0.9.0
    - dask-core
    - datashape >=0.5.1
    - numba >=0.51
    - pandas >=0.24.1
    - param >=1.6.1
    - pillow >=3.1.1
    - pyct >=0.4.5
    - scipy
    - xarray >=0.9.6

test:
  requires:
    - pip
    - fastparquet >=0.1.6
    - flake8
    - nbsmoke >0.5.0
    - pytest >=3.9.3
    - pytest-benchmark >=3.0.0
    - holoviews >=1.10.0
    - netcdf4

  imports:
    - datashader
  commands:
    - pip check || true    # [not win]
    - pip check || exit 0  # [win]
    - datashader --help
    - datashader copy-examples --path=. --force
    # just run one notebook for now; increase in the future if notebooks can be run quickly with test/tiny data
    - pytest --nbsmoke-run -k ".ipynb" getting_started/2_Pipeline.ipynb

about:
  home: https://datashader.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Data visualization toolchain based on aggregating into a grid
  description: |
    Datashader is a data rasterization pipeline for automating the process of
    creating meaningful representations of large amounts of data.
  doc_url: https://datashader.org
  dev_url: https://github.com/holoviz/datashader

extra:
  recipe-maintainers:
    - jbednar
    - ocefpaf
    - philippjfr
    - jsignell
