{% set name = "datashader" %}
{% set version = "0.6.6" %}
{% set sha256 = "fe0a3d96203a4af2c55e6ecf6ccb5d993e2f7ea3b03220e25108744e1fe0d73f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - datashader = datashader.__main__:main

requirements:
  host:
    - python
    - pip
    - param >=1.6.1
  run:
    - python
    - dask >=0.15.4
    - datashape >=0.5.1
    - numba >=0.37.0
    - numpy >=1.7
    - pandas >=0.20.3
    - pillow >=3.1.1
    - xarray >=0.9.6
    - toolz >=0.7.4
    - colorcet >=0.9.0
    - param >=1.6.0
    - pyct
    - scikit-image
    - bokeh
    - scipy

test:
  requires:
    - pytest >=2.8.5
    - pytest-benchmark >=3.0.0
  imports:
    - datashader
  commands:                                                                         # [not win32 and not linux32]
    - pytest --pyargs --doctest-modules --doctest-ignore-import-errors datashader   # [not win32 and not linux32]
    - datashader copy-examples --path=. --force                                     # [not win32 and not linux32]
    - datashader fetch-data --path=. --datasets small.yml                           # [not win32 and not linux32]
    # TODO add notebook test once nbsmoke is available

about:
  home: http://datashader.org
  license: New BSD
  license_file: LICENSE.txt
  summary: 'Data visualization toolchain based on aggregating into a grid'

  description: |
    Datashader is a data rasterization pipeline for automating the process of
    creating meaningful representations of large amounts of data.
  doc_url: http://datashader.org
  dev_url: https://github.com/bokeh/datashader

extra:
  recipe-maintainers:
    - jbednar
    - jbcrail
    - msarahan
