travis:
  secure:
    BINSTAR_TOKEN: rMZKDEA88PMcRHtK/073oqCcc/R7sWbzn15og92i7SPdrHVcEFduF42+D+J+evghIX5QBTsjrGqpASdAuH6nTgN74swgOssNRHXxRcv9sNPP8ZoccklrXbWKnzzM8ThJOGM+4ZMNg+r+wxVdq/SVAE7PenWXWk89TOrpr3GoCWXsyTNli2OALgiVNMmFoaR0H2o37/XJ0BDyLBDhoXrp1GldbLjvYWKtH7c1QikRjMp+RB2ifAyJuYpfshInQD8sv+zEXhNSgNpNx6egZ313E8PBmGDn22M5erwm0B8RFVLIQ06IIN5ls8sWfcvyyRYmkE/A9J1qGP2j+EVGylF/aitK6zNRTVI+R9c/OCKEPxEEbPa9zaq29f7Nhs4mauzTvfA1cYfYsMEDUX4aFw9b9uw/LashkSqU1wEK/x74p/bs4sKGM/0xxY/scYfUP9IaJIjM2Q3AlljfUIZbJI7M9ehDpit3IKNy+fwdwHIDF6WWF2o2akm76G/LSInXnlWq/v1R78tew/mB1BFk+LHPg+glJ7kKMzpCeAfoQ5fUDS5/NsKgI8OdseV6JVVvW9Z0+/F1apwchdjqccb/1UPkYjliajpTnUFI/mXx0aokQPhxuYtWBOMtiPPxZh4QztYvT6hJUyXrXe3uasE4vaJCZIECTyyyu9nQ/FRuVDqxnQU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
