travis:
  secure:
    BINSTAR_TOKEN: ZWtVizkrKA8ybK1AjqUTVJfKPIOmkl0TbMDwtLMcFBN2HekABv7fANGfVzoYwYZaFTK9YRITXc3cRVCTaRRgJip1acQg0lgAeG4w8xtoQdCnKVier9WEiobhCBgWzYfCNEMVesC7t+RzP6xVl1p6IgzbdAckPi5Q+Nw9iI+1eFxMssX5CRB2X3k6T12XPBucKNDYZqnKniDvT2zD/zv/0izttANZ+x9vd+1Pqq3uiFWRGbyyJTNiYWCODqdfzpS4jKcBkH6pSg8jxXAkzc1MM17EvJ1JjQrCfk/sdRN8XA6fQtfwC+0V763Eg8yImaI97581+zC5kJ6hrMlQseB03ftsGqqItELAl+vSX5i0O0EtA2ZqeJkczyUP6mLES+M2IOdrv1gZEgVVdhIctDWD0DMKrR2Y+E+2gYsDPM6jxA8ZRLk7Z4PVz2n5eUABeAiMtZRoe9BdwZXUtg9hnP0dQPRV1PPpsFvBLGegF3XxF9PZZ0wwL5aXsVchumW3sLrbTvg5oE9mrTa6FHVCX4vxJmzG6L5eelWBAuxloYo2H/qBZ55E9VPaol8aLwZ+XSalIAIfRfACpRurv2XAZbGN3JSk6O+141HpkdYlFz50C9aS3Pf9iKoKrXcU+feboWR2D9f4TgtWGX7PEkjfoUvIjm3pyfkO60mIfODsWTtKGqw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
